// Code generated by AI, will be rewritten by hand later to clean up and expand functionality. For now, this is a quick and dirty implementation to get the basic functionality working for personal use.

function generateId() {
    return Date.now().toString(36) + Math.random().toString(36).slice(2);
}

function getStoredResults() {
    const stored = JSON.parse(localStorage.getItem('calsPerDollarResults')) || [];
    const normalized = stored.map(item => {
        if (typeof item === 'string') {
            return { id: generateId(), text: item };
        }
        return item;
    });
    return normalized;
}

function saveStoredResults(results) {
    localStorage.setItem('calsPerDollarResults', JSON.stringify(results));
}

function createResultItem(result) {
    const resultItem = document.createElement('li');
    
    // Format text with bold labels
    let formattedText = result.text;
    formattedText = formattedText.replace(/^([^:]+):/g, '<strong>$1</strong>:');
    formattedText = formattedText.replace(/Total Cals/g, '<strong>Total Cals</strong>');
    formattedText = formattedText.replace(/Cals\/\$/g, '<strong>Cals/$</strong>');
    formattedText = formattedText.replace(/Total P/g, '<strong>Total P</strong>');
    formattedText = formattedText.replace(/P\/\$/g, '<strong>P/$</strong>');
    
    resultItem.innerHTML = formattedText;

    const deleteButton = document.createElement('button');
    deleteButton.type = 'button';
    deleteButton.textContent = 'Delete';
    deleteButton.style.marginLeft = '0.75rem';
    deleteButton.addEventListener('click', () => {
        const results = getStoredResults().filter(r => r.id !== result.id);
        saveStoredResults(results);
        resultItem.remove();
    });

    resultItem.appendChild(deleteButton);
    return resultItem;
}

function calculate() {
    const name = document.getElementById('itemName').value;
    const servings = parseFloat(document.getElementById('servings').value);
    const calsPerServing = parseFloat(document.getElementById('calsPerServing').value);
    const price = parseFloat(document.getElementById('price').value);

    if (isNaN(servings) || isNaN(calsPerServing) || isNaN(price) || servings <= 0 || price <= 0) {
        alert('Please enter valid numbers for servings, calories per serving, and price.');
        return;
    }

    const totalCalories = servings * calsPerServing;
    const calsPerDollar = totalCalories / price;
    const proteinPerServing = parseFloat(document.getElementById('proteinPerServing').value);

    let resultText = `${name}: Total Cals ${totalCalories.toFixed(0)}, Cals/$ ${calsPerDollar.toFixed(0)}`;
    
    if (!isNaN(proteinPerServing)) {
        const totalProtein = servings * proteinPerServing;
        const proteinPerDollar = totalProtein / price;
        resultText += `, Total P ${totalProtein.toFixed(0)}, P/$ ${proteinPerDollar.toFixed(0)}`;
    }

    const result = { id: generateId(), text: resultText };
    const results = getStoredResults();
    results.push(result);
    saveStoredResults(results);

    const resultsList = document.getElementById('results');
    resultsList.appendChild(createResultItem(result));

    document.getElementById('itemName').value = '';
    document.getElementById('servings').value = '';
    document.getElementById('calsPerServing').value = '';
    document.getElementById('proteinPerServing').value = '';
    document.getElementById('price').value = '';
}

function loadResults() {
    const results = getStoredResults();
    const resultsList = document.getElementById('results');
    
    results.forEach(result => {
        resultsList.appendChild(createResultItem(result));
    });
    saveStoredResults(results);
}

function clearResults() {
    document.getElementById('results').innerHTML = '';
    localStorage.removeItem('calsPerDollarResults');
}

// Load results on page load
document.addEventListener('DOMContentLoaded', loadResults);
